# Generated by Django 3.2.16 on 2024-06-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
    ]
